Issue/ppss-39595
PROSPricing/application-browser pull request #4
Opened 2020-10-05 21:37 UTC by caeduroa

PR for releasing 4.0.1 version.

2020-10-08 16:47 UTC, kevinmprince approved these changes

2020-10-15 20:24 UTC, wrprice requested changes

2020-10-15 20:24 UTC, wrprice commented on changeWinMaker.js
> +/*
You can't use this proprietary license in this GPL project.

2020-10-15 20:24 UTC, wrprice commented on setRepositoryURL.js
> + * This software is the confidential and proprietary information of
Cannot use proprietary license with GPL project

2020-10-15 20:24 UTC, wrprice commented on src/about.html
> +              /*const htmlExtensions = Array('html', 'htm');
This block of code is commented out, but relates to third-party licenses.  Should it actually be removed?  If so, actually remove it along with the comment line above.  If it was in error, please remove the comment block markers.

2020-10-15 21:06 UTC, wrprice approved these changes

2020-10-15 21:07 UTC, merged